//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiscInventory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MISC_INVENTORYEntities1 : DbContext
    {
        public MISC_INVENTORYEntities1()
            : base("name=MISC_INVENTORYEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T115_MISC_INVENTORY> T115_MISC_INVENTORY { get; set; }
        public DbSet<T115_MISC_TRAN_ARCHV> T115_MISC_TRAN_ARCHV { get; set; }
        public DbSet<T115_MISC_TRANS> T115_MISC_TRANS { get; set; }
    }
}
