//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiscInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T000_SYSTEM_SEC
    {
        public string SYSTEM_ID { get; set; }
        public string USERID_R { get; set; }
        public string BUDGET { get; set; }
        public string FUNCTIONAL_AREA { get; set; }
        public string PRIORITY { get; set; }
        public string DEFAULT_PANEL { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string T000_SYSTEM_SEC_PRIMARY_KEY { get; set; }
    }
}
